# Generated by Django 2.2 on 2020-08-31 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200825_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time_post_created',
            new_name='timestamp',
        ),
    ]
