# Generated by Django 2.2 on 2020-08-31 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200831_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='time_liked',
            new_name='timestamp',
        ),
    ]
