# Generated by Django 2.2 on 2020-09-04 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_proile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='proile_image',
            new_name='profile_image',
        ),
    ]
