# Generated by Django 2.2 on 2020-09-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20200905_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
